visibility=public
kind=defined
names=put2,request_put

--- request_put(path, data, initheader = nil)
--- request_put(path, data, initheader = nil) {|response| .... }
--- put2(path, data, initheader = nil)
--- put2(path, data, initheader = nil) {|response| .... }


